-- Mawada Phone - 1. DROP ALL (Run First)
-- ============================================
-- 1. DROP ALL RLS POLICIES
-- ============================================
DROP POLICY IF EXISTS "Users view own orders" ON public.orders;
DROP POLICY IF EXISTS "Users can create orders" ON public.orders;
DROP POLICY IF EXISTS "Users can update own orders" ON public.orders;
DROP POLICY IF EXISTS "Admins manage all orders" ON public.orders;
DROP POLICY IF EXISTS orders_select ON public.orders;
DROP POLICY IF EXISTS orders_insert ON public.orders;
DROP POLICY IF EXISTS orders_update ON public.orders;
DROP POLICY IF EXISTS orders_delete ON public.orders;
DROP POLICY IF EXISTS "Users view own order items" ON public.order_items;
DROP POLICY IF EXISTS "Admins manage all order items" ON public.order_items;
DROP POLICY IF EXISTS order_items_select ON public.order_items;
DROP POLICY IF EXISTS order_items_insert ON public.order_items;
DROP POLICY IF EXISTS order_items_update ON public.order_items;
DROP POLICY IF EXISTS order_items_delete ON public.order_items;
DROP POLICY IF EXISTS "Users manage own cart" ON public.cart_items;
DROP POLICY IF EXISTS cart_items_select ON public.cart_items;
DROP POLICY IF EXISTS cart_items_insert ON public.cart_items;
DROP POLICY IF EXISTS cart_items_update ON public.cart_items;
DROP POLICY IF EXISTS cart_items_delete ON public.cart_items;
DROP POLICY IF EXISTS "Users manage own wishlist" ON public.wishlist_items;
DROP POLICY IF EXISTS wishlist_items_select ON public.wishlist_items;
DROP POLICY IF EXISTS wishlist_items_insert ON public.wishlist_items;
DROP POLICY IF EXISTS wishlist_items_update ON public.wishlist_items;
DROP POLICY IF EXISTS wishlist_items_delete ON public.wishlist_items;
DROP POLICY IF EXISTS "Users manage own addresses" ON public.addresses;
DROP POLICY IF EXISTS addresses_select ON public.addresses;
DROP POLICY IF EXISTS addresses_insert ON public.addresses;
DROP POLICY IF EXISTS addresses_update ON public.addresses;
DROP POLICY IF EXISTS addresses_delete ON public.addresses;
DROP POLICY IF EXISTS "Users view own notifications" ON public.notifications;
DROP POLICY IF EXISTS "Users update own notifications" ON public.notifications;
DROP POLICY IF EXISTS "Admins can create notifications" ON public.notifications;
DROP POLICY IF EXISTS notifications_select ON public.notifications;
DROP POLICY IF EXISTS notifications_insert ON public.notifications;
DROP POLICY IF EXISTS notifications_update ON public.notifications;
DROP POLICY IF EXISTS notifications_delete ON public.notifications;
DROP POLICY IF EXISTS "Users view own profile" ON public.profiles;
DROP POLICY IF EXISTS "Users can update own profile" ON public.profiles;
DROP POLICY IF EXISTS "Admins view all profiles" ON public.profiles;
DROP POLICY IF EXISTS profiles_select ON public.profiles;
DROP POLICY IF EXISTS profiles_insert ON public.profiles;
DROP POLICY IF EXISTS profiles_update ON public.profiles;
DROP POLICY IF EXISTS profiles_delete ON public.profiles;
DROP POLICY IF EXISTS "Anyone can view active products" ON public.products;
DROP POLICY IF EXISTS "Admins can manage products" ON public.products;
DROP POLICY IF EXISTS products_select ON public.products;
DROP POLICY IF EXISTS products_insert ON public.products;
DROP POLICY IF EXISTS products_update ON public.products;
DROP POLICY IF EXISTS products_delete ON public.products;
DROP POLICY IF EXISTS "Anyone can view categories" ON public.categories;
DROP POLICY IF EXISTS "Admins can manage categories" ON public.categories;
DROP POLICY IF EXISTS categories_select ON public.categories;
DROP POLICY IF EXISTS categories_insert ON public.categories;
DROP POLICY IF EXISTS categories_update ON public.categories;
DROP POLICY IF EXISTS categories_delete ON public.categories;
DROP POLICY IF EXISTS "Anyone can view brands" ON public.brands;
DROP POLICY IF EXISTS "Admins can manage brands" ON public.brands;
DROP POLICY IF EXISTS brands_select ON public.brands;
DROP POLICY IF EXISTS brands_insert ON public.brands;
DROP POLICY IF EXISTS brands_update ON public.brands;
DROP POLICY IF EXISTS brands_delete ON public.brands;
DROP POLICY IF EXISTS "Anyone can view active banners" ON public.banners;
DROP POLICY IF EXISTS "Admins can manage banners" ON public.banners;
DROP POLICY IF EXISTS banners_select ON public.banners;
DROP POLICY IF EXISTS banners_insert ON public.banners;
DROP POLICY IF EXISTS banners_update ON public.banners;
DROP POLICY IF EXISTS banners_delete ON public.banners;
DROP POLICY IF EXISTS "Anyone can view branches" ON public.branches;
DROP POLICY IF EXISTS "Admins can manage branches" ON public.branches;
DROP POLICY IF EXISTS branches_select ON public.branches;
DROP POLICY IF EXISTS branches_insert ON public.branches;
DROP POLICY IF EXISTS branches_update ON public.branches;
DROP POLICY IF EXISTS branches_delete ON public.branches;
DROP POLICY IF EXISTS "Anyone can view product images" ON public.product_images;
DROP POLICY IF EXISTS "Admins manage product images" ON public.product_images;
DROP POLICY IF EXISTS product_images_select ON public.product_images;
DROP POLICY IF EXISTS product_images_insert ON public.product_images;
DROP POLICY IF EXISTS product_images_update ON public.product_images;
DROP POLICY IF EXISTS product_images_delete ON public.product_images;
DROP POLICY IF EXISTS "Anyone can view product variants" ON public.product_variants;
DROP POLICY IF EXISTS "Admins manage product variants" ON public.product_variants;
DROP POLICY IF EXISTS product_variants_select ON public.product_variants;
DROP POLICY IF EXISTS product_variants_insert ON public.product_variants;
DROP POLICY IF EXISTS product_variants_update ON public.product_variants;
DROP POLICY IF EXISTS product_variants_delete ON public.product_variants;
DROP POLICY IF EXISTS "Anyone can view specifications" ON public.specifications;
DROP POLICY IF EXISTS "Admins manage specifications" ON public.specifications;
DROP POLICY IF EXISTS specifications_select ON public.specifications;
DROP POLICY IF EXISTS specifications_insert ON public.specifications;
DROP POLICY IF EXISTS specifications_update ON public.specifications;
DROP POLICY IF EXISTS specifications_delete ON public.specifications;
DROP POLICY IF EXISTS "Anyone can view reviews" ON public.reviews;
DROP POLICY IF EXISTS "Users can create reviews" ON public.reviews;
DROP POLICY IF EXISTS "Users can update own reviews" ON public.reviews;
DROP POLICY IF EXISTS "Admins manage all reviews" ON public.reviews;
DROP POLICY IF EXISTS reviews_select ON public.reviews;
DROP POLICY IF EXISTS reviews_insert ON public.reviews;
DROP POLICY IF EXISTS reviews_update ON public.reviews;
DROP POLICY IF EXISTS reviews_delete ON public.reviews;
DROP POLICY IF EXISTS "Product images public read" ON storage.objects;
DROP POLICY IF EXISTS "Admin upload product images" ON storage.objects;
DROP POLICY IF EXISTS "Admin delete product images" ON storage.objects;
DROP POLICY IF EXISTS "Banner images public read" ON storage.objects;
DROP POLICY IF EXISTS "Admin upload banner images" ON storage.objects;
DROP POLICY IF EXISTS "Admin delete banner images" ON storage.objects;
DROP POLICY IF EXISTS "Avatars public read" ON storage.objects;
DROP POLICY IF EXISTS "Users upload own avatar" ON storage.objects;

-- 2. DROP TRIGGERS
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
DROP FUNCTION IF EXISTS public.handle_new_user() CASCADE;
DROP FUNCTION IF EXISTS public.get_top_products(integer) CASCADE;

-- 3. DROP ALL TABLES
DROP TABLE IF EXISTS public.reviews CASCADE;
DROP TABLE IF EXISTS public.specifications CASCADE;
DROP TABLE IF EXISTS public.product_variants CASCADE;
DROP TABLE IF EXISTS public.product_images CASCADE;
DROP TABLE IF EXISTS public.order_items CASCADE;
DROP TABLE IF EXISTS public.orders CASCADE;
DROP TABLE IF EXISTS public.wishlist_items CASCADE;
DROP TABLE IF EXISTS public.cart_items CASCADE;
DROP TABLE IF EXISTS public.addresses CASCADE;
DROP TABLE IF EXISTS public.notifications CASCADE;
DROP TABLE IF EXISTS public.products CASCADE;
DROP TABLE IF EXISTS public.categories CASCADE;
DROP TABLE IF EXISTS public.brands CASCADE;
DROP TABLE IF EXISTS public.banners CASCADE;
DROP TABLE IF EXISTS public.branches CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;

-- 4. DROP CUSTOM TYPES
DROP TYPE IF EXISTS "OrderStatus" CASCADE;
DROP TYPE IF EXISTS "PaymentStatus" CASCADE;
DROP TYPE IF EXISTS "DiscountType" CASCADE;
DROP TYPE IF EXISTS "NotificationType" CASCADE;

-- 5. DROP INDEXES
DROP INDEX IF EXISTS idx_products_category;
DROP INDEX IF EXISTS idx_products_active;
DROP INDEX IF EXISTS idx_products_featured;
DROP INDEX IF EXISTS idx_product_images_product;
DROP INDEX IF EXISTS idx_product_variants_product;
DROP INDEX IF EXISTS idx_specifications_product;
DROP INDEX IF EXISTS idx_cart_user;
DROP INDEX IF EXISTS idx_wishlist_user;
DROP INDEX IF EXISTS idx_orders_user;
DROP INDEX IF EXISTS idx_orders_status;
DROP INDEX IF EXISTS idx_order_items_order;
DROP INDEX IF EXISTS idx_addresses_user;
DROP INDEX IF EXISTS idx_notifications_user;
DROP INDEX IF EXISTS idx_notifications_read;
DROP INDEX IF EXISTS idx_reviews_product;
